from __future__ import annotations

from typing import Any

from app.models import OrganizationType

# National reference entries use concrete two-character codes because the database
# intentionally stores State/UT codes in varchar(2) arrays.
ALL_STATE_CODES = [
    "AN",
    "AP",
    "AR",
    "AS",
    "BR",
    "CH",
    "CG",
    "DD",
    "DL",
    "GA",
    "GJ",
    "HR",
    "HP",
    "JK",
    "JH",
    "KA",
    "KL",
    "LA",
    "LD",
    "MP",
    "MH",
    "MN",
    "ML",
    "MZ",
    "NL",
    "OD",
    "PY",
    "PB",
    "RJ",
    "SK",
    "TN",
    "TS",
    "TR",
    "UP",
    "UK",
    "WB",
]

CONTENT_REPHRASED_NOTICE = (
    "Content was rephrased for compliance with licensing restrictions. "
    "The linked official notification controls eligibility, benefits, dates, and selection."
)


def _organization(
    key: str,
    display_name: str,
    organization_type: OrganizationType,
    state: str | None = None,
) -> dict[str, Any]:
    return {
        "key": key,
        "slug": f"{key}-scholarship-reference",
        "legal_name": f"{display_name} — Public-source reference catalogue",
        "display_name": f"{display_name} — Reference",
        "type": organization_type,
        "state": state,
        "publisher_login": f"{key}.catalog@demo.scholarsaathi.local",
    }


REFERENCE_ORGANIZATION_SPECS = [
    _organization(
        "goi", "Government of India Scholarship Schemes", OrganizationType.CENTRAL_GOVERNMENT
    ),
    _organization(
        "west_bengal", "Government of West Bengal", OrganizationType.STATE_GOVERNMENT, "WB"
    ),
    _organization("odisha_ref", "Government of Odisha", OrganizationType.STATE_GOVERNMENT, "OD"),
    _organization("gujarat", "Government of Gujarat", OrganizationType.STATE_GOVERNMENT, "GJ"),
    _organization(
        "maharashtra", "Government of Maharashtra", OrganizationType.STATE_GOVERNMENT, "MH"
    ),
    _organization("karnataka", "Government of Karnataka", OrganizationType.STATE_GOVERNMENT, "KA"),
    _organization("kerala", "Government of Kerala", OrganizationType.STATE_GOVERNMENT, "KL"),
    _organization(
        "tamil_nadu", "Government of Tamil Nadu", OrganizationType.STATE_GOVERNMENT, "TN"
    ),
    _organization("telangana", "Government of Telangana", OrganizationType.STATE_GOVERNMENT, "TS"),
    _organization(
        "andhra_pradesh", "Government of Andhra Pradesh", OrganizationType.STATE_GOVERNMENT, "AP"
    ),
    _organization(
        "madhya_pradesh", "Government of Madhya Pradesh", OrganizationType.STATE_GOVERNMENT, "MP"
    ),
    _organization("rajasthan", "Government of Rajasthan", OrganizationType.STATE_GOVERNMENT, "RJ"),
    _organization(
        "uttar_pradesh", "Government of Uttar Pradesh", OrganizationType.STATE_GOVERNMENT, "UP"
    ),
    _organization("bihar", "Government of Bihar", OrganizationType.STATE_GOVERNMENT, "BR"),
    _organization("jharkhand", "Government of Jharkhand", OrganizationType.STATE_GOVERNMENT, "JH"),
    _organization("haryana", "Government of Haryana", OrganizationType.STATE_GOVERNMENT, "HR"),
    _organization("punjab", "Government of Punjab", OrganizationType.STATE_GOVERNMENT, "PB"),
    _organization(
        "himachal_pradesh",
        "Government of Himachal Pradesh",
        OrganizationType.STATE_GOVERNMENT,
        "HP",
    ),
    _organization("assam", "Government of Assam", OrganizationType.STATE_GOVERNMENT, "AS"),
    _organization(
        "uttarakhand", "Government of Uttarakhand", OrganizationType.STATE_GOVERNMENT, "UK"
    ),
    _organization(
        "chhattisgarh", "Government of Chhattisgarh", OrganizationType.STATE_GOVERNMENT, "CG"
    ),
    _organization("reliance_foundation", "Reliance Foundation", OrganizationType.NGO),
    _organization("sbi_foundation", "SBI Foundation", OrganizationType.NGO),
    _organization("hdfc_bank", "HDFC Bank Parivartan", OrganizationType.PRIVATE_COMPANY),
    _organization("kotak_foundation", "Kotak Education Foundation", OrganizationType.NGO),
    _organization("tata_capital", "Tata Capital", OrganizationType.PRIVATE_COMPANY),
    _organization("wipro_cares", "Wipro Cares", OrganizationType.NGO),
    _organization("ffe", "Foundation For Excellence", OrganizationType.NGO),
    _organization("colgate", "Colgate-Palmolive India", OrganizationType.PRIVATE_COMPANY),
    _organization("loreal", "L'Oréal India", OrganizationType.PRIVATE_COMPANY),
]


def _scheme(
    slug: str,
    organization: str,
    title: str,
    summary: str,
    states: list[str],
    levels: list[str],
    courses: list[str],
    tags: list[str],
    official_source_url: str,
    eligibility: str,
    benefit: str = "Financial assistance is provided according to the current official scheme notification.",
) -> dict[str, Any]:
    return {
        "slug": slug,
        "organization": organization,
        "title": title,
        "summary": summary,
        "states": states,
        "levels": levels,
        "courses": courses,
        "tags": tags,
        "official_source_url": official_source_url,
        "eligibility": eligibility,
        "benefit": benefit,
    }


# Twenty Central Government schemes. Names and links point to the respective official
# government/NSP sources; cycle-specific amounts and deadlines are deliberately not invented.
CENTRAL_SCHOLARSHIP_SPECS = [
    _scheme(
        "central-sector-scholarship-college-university-students",
        "goi",
        "Central Sector Scheme of Scholarship for College and University Students",
        "Merit-linked higher-education support administered through the National Scholarship Portal.",
        ALL_STATE_CODES,
        ["UNDERGRADUATE", "POSTGRADUATE"],
        ["ALL_RECOGNIZED_COURSES"],
        ["CENTRAL_GOVERNMENT", "MERIT", "INCOME"],
        "https://www.education.gov.in/scholarships-education-loan-0",
        "Students pursuing regular college or university study should check the current Ministry of Education notification for board-result, income, course, and renewal conditions.",
    ),
    _scheme(
        "national-means-cum-merit-scholarship-scheme",
        "goi",
        "National Means-cum-Merit Scholarship Scheme",
        "School scholarship intended to reduce secondary-stage dropout among economically weaker learners.",
        ALL_STATE_CODES,
        ["CLASS_9_12"],
        ["SCHOOL_EDUCATION"],
        ["CENTRAL_GOVERNMENT", "SCHOOL", "MERIT", "INCOME"],
        "https://www.education.gov.in/en/nmms",
        "Eligible Class VIII learners take the State or UT selection process for scholarship support beginning in Class IX, subject to the current official rules.",
        "The Ministry of Education currently describes an annual scholarship for selected learners with renewal through the secondary stage.",
    ),
    _scheme(
        "aicte-pragati-scholarship-girl-students",
        "goi",
        "AICTE Pragati Scholarship Scheme for Girl Students",
        "AICTE support for girls pursuing approved diploma or degree-level technical education.",
        ALL_STATE_CODES,
        ["DIPLOMA", "UNDERGRADUATE"],
        ["BTECH", "BE", "TECHNICAL_DIPLOMA"],
        ["CENTRAL_GOVERNMENT", "WOMEN", "TECHNICAL_EDUCATION"],
        "https://www.aicte-india.org/bureaus/rifd/Scholarship-Schemes",
        "Girl students admitted to eligible AICTE-approved technical programmes should verify admission year, family, income, and renewal conditions in the current notice.",
    ),
    _scheme(
        "aicte-saksham-scholarship-students-with-disabilities",
        "goi",
        "AICTE Saksham Scholarship Scheme for Specially-Abled Students",
        "AICTE educational support for students with disabilities in approved technical programmes.",
        ALL_STATE_CODES,
        ["DIPLOMA", "UNDERGRADUATE"],
        ["BTECH", "BE", "TECHNICAL_DIPLOMA"],
        ["CENTRAL_GOVERNMENT", "DISABILITY", "TECHNICAL_EDUCATION"],
        "https://www.aicte-india.org/bureaus/rifd/Scholarship-Schemes",
        "Students with the disability benchmark and admission conditions stated by AICTE should check the current notification before applying.",
    ),
    _scheme(
        "aicte-swanath-scholarship-scheme",
        "goi",
        "AICTE Swanath Scholarship Scheme",
        "AICTE support for eligible students affected by orphanhood, the COVID-19 pandemic, or specified armed-forces circumstances.",
        ALL_STATE_CODES,
        ["DIPLOMA", "UNDERGRADUATE"],
        ["BTECH", "BE", "TECHNICAL_DIPLOMA"],
        ["CENTRAL_GOVERNMENT", "ORPHAN", "TECHNICAL_EDUCATION"],
        "https://www.aicte-india.org/bureaus/rifd/Scholarship-Schemes",
        "Applicants must fall within a beneficiary category and programme type listed in the current AICTE Swanath guidelines.",
    ),
    _scheme(
        "ishan-uday-special-scholarship-north-eastern-region",
        "goi",
        "Ishan Uday Special Scholarship Scheme for North Eastern Region",
        "UGC scholarship supporting higher education for students domiciled in the North Eastern Region.",
        ["AR", "AS", "MN", "ML", "MZ", "NL", "SK", "TR"],
        ["UNDERGRADUATE"],
        ["ALL_UNDERGRADUATE"],
        ["CENTRAL_GOVERNMENT", "NORTH_EAST", "UNDERGRADUATE"],
        "https://www.ugc.gov.in/pdfnews/3558377_final-NER-guidelines-with-annexures.pdf",
        "Students from the North Eastern Region entering recognized general, professional, technical, medical, or paramedical undergraduate study should check current domicile, income, and admission rules.",
    ),
    _scheme(
        "pg-indira-gandhi-scholarship-single-girl-child",
        "goi",
        "PG Indira Gandhi Scholarship for Single Girl Child",
        "UGC postgraduate scholarship supporting eligible single girl children.",
        ALL_STATE_CODES,
        ["POSTGRADUATE"],
        ["ALL_RECOGNIZED_COURSES"],
        ["CENTRAL_GOVERNMENT", "WOMEN", "SINGLE_GIRL_CHILD"],
        "https://www.ugc.gov.in/Bureaus/bureaus_details?HTh8DxmdOv4wCVphfLaNizbBCW4vd1y/CAAlRY19DTL1MpdRIQTYCflmu5VUMUdP8WUiVKPwYNtZGqLgqiaKLw%3D%3D",
        "Single girl children entering eligible postgraduate study should verify age, programme mode, institution, and family-status conditions in the current UGC notice.",
    ),
    _scheme(
        "pg-scholarship-university-rank-holders",
        "goi",
        "PG Scholarship for University Rank Holders",
        "UGC support for eligible undergraduate rank holders continuing into postgraduate education.",
        ALL_STATE_CODES,
        ["POSTGRADUATE"],
        ["ALL_RECOGNIZED_COURSES"],
        ["CENTRAL_GOVERNMENT", "MERIT", "UNIVERSITY_RANK"],
        "https://www.ugc.gov.in/page/scholarships-and-fellowships.aspx",
        "Undergraduate rank holders admitted to eligible postgraduate programmes should consult the current UGC subject, rank, age, and institution rules.",
    ),
    _scheme(
        "aicte-postgraduate-scholarship-gate-gpat-ceed",
        "goi",
        "AICTE Post Graduate Scholarship for GATE, GPAT and CEED Qualified Students",
        "Postgraduate assistance for eligible students with qualifying national examination scores.",
        ALL_STATE_CODES,
        ["POSTGRADUATE"],
        ["MTECH", "MPHARM", "MDES"],
        ["CENTRAL_GOVERNMENT", "GATE", "GPAT", "CEED"],
        "https://www.aicte-india.org/schemes/students-development-schemes/PG-Scholarship-Scheme",
        "Full-time students admitted to eligible AICTE-approved postgraduate programmes with a valid qualifying score should check the latest rules.",
    ),
    _scheme(
        "prime-ministers-scholarship-capf-assam-rifles",
        "goi",
        "Prime Minister's Scholarship Scheme for Central Armed Police Forces and Assam Rifles",
        "Merit-based higher-education assistance for eligible wards and widows of CAPF and Assam Rifles personnel.",
        ALL_STATE_CODES,
        ["UNDERGRADUATE", "POSTGRADUATE"],
        ["PROFESSIONAL_COURSES"],
        ["CENTRAL_GOVERNMENT", "CAPF", "MERIT"],
        "https://scholarships.gov.in/All-Scholarships",
        "Eligible wards or widows pursuing approved professional study should verify service-category, marks, course, and priority conditions on NSP.",
    ),
    _scheme(
        "prime-ministers-scholarship-rpf-rpsf",
        "goi",
        "Prime Minister's Scholarship Scheme for RPF and RPSF",
        "Higher-education scholarship for eligible wards of Railway Protection Force and Railway Protection Special Force personnel.",
        ALL_STATE_CODES,
        ["UNDERGRADUATE", "POSTGRADUATE"],
        ["PROFESSIONAL_COURSES"],
        ["CENTRAL_GOVERNMENT", "RPF", "MERIT"],
        "https://scholarships.gov.in/All-Scholarships",
        "Eligible wards entering an approved professional programme should check current service, merit, course, and renewal conditions on NSP.",
    ),
    _scheme(
        "pm-yasasvi-top-class-school-education",
        "goi",
        "PM-YASASVI Top Class School Education for OBC, EBC and DNT Students",
        "Central-sector school education support for eligible OBC, EBC and DNT learners in notified institutions.",
        ALL_STATE_CODES,
        ["CLASS_9_12"],
        ["SCHOOL_EDUCATION"],
        ["CENTRAL_GOVERNMENT", "OBC", "EBC", "DNT"],
        "https://socialjustice.gov.in/writereaddata/UploadFile/84741700556379.pdf",
        "OBC, EBC and DNT learners studying in a notified school should verify class, income, institution, and selection conditions in the current guidelines.",
    ),
    _scheme(
        "pm-yasasvi-top-class-college-education",
        "goi",
        "PM-YASASVI Top Class College Education for OBC, EBC and DNT Students",
        "Higher-education support for eligible OBC, EBC and DNT students in notified institutions.",
        ALL_STATE_CODES,
        ["UNDERGRADUATE", "POSTGRADUATE"],
        ["ALL_RECOGNIZED_COURSES"],
        ["CENTRAL_GOVERNMENT", "OBC", "EBC", "DNT"],
        "https://socialjustice.gov.in/schemes/101",
        "OBC, EBC and DNT students admitted to a notified institution should verify income, programme, institution, and award conditions in the current notification.",
    ),
    _scheme(
        "pm-yasasvi-post-matric-obc-ebc-dnt",
        "goi",
        "PM-YASASVI Post-Matric Scholarship for OBC, EBC and DNT Students",
        "Post-matric financial assistance for eligible OBC, EBC and DNT learners.",
        ALL_STATE_CODES,
        ["CLASS_11_12", "DIPLOMA", "UNDERGRADUATE", "POSTGRADUATE"],
        ["ALL_RECOGNIZED_COURSES"],
        ["CENTRAL_GOVERNMENT", "OBC", "EBC", "DNT", "POST_MATRIC"],
        "https://socialjustice.gov.in/writereaddata/UploadFile/pmsdnt.pdf",
        "Post-matric OBC, EBC and DNT students should verify category, domicile, income, programme group, and state implementation rules.",
    ),
    _scheme(
        "post-matric-scholarship-scheduled-caste-students",
        "goi",
        "Post-Matric Scholarship for Scheduled Caste Students",
        "Centrally sponsored assistance enabling eligible SC students to continue post-matric education.",
        ALL_STATE_CODES,
        ["CLASS_11_12", "DIPLOMA", "UNDERGRADUATE", "POSTGRADUATE"],
        ["ALL_RECOGNIZED_COURSES"],
        ["CENTRAL_GOVERNMENT", "SC", "POST_MATRIC"],
        "https://socialjustice.gov.in/common/19536",
        "SC students pursuing recognized post-matric study should check income, course-group, domicile, and state or UT implementation conditions.",
    ),
    _scheme(
        "top-class-education-scheduled-caste-students",
        "goi",
        "Top Class Education Scheme for Scheduled Caste Students",
        "Central-sector support for eligible SC students admitted to notified institutions.",
        ALL_STATE_CODES,
        ["UNDERGRADUATE", "POSTGRADUATE"],
        ["ALL_RECOGNIZED_COURSES"],
        ["CENTRAL_GOVERNMENT", "SC", "TOP_CLASS_EDUCATION"],
        "https://socialjustice.gov.in/schemes/27",
        "SC students admitted to a notified institution should verify income, programme, institution, and slot conditions in the current scheme notice.",
    ),
    _scheme(
        "national-overseas-scholarship-scheduled-caste-others",
        "goi",
        "National Overseas Scholarship for Scheduled Caste and Other Eligible Students",
        "Overseas higher-education support under the Ministry of Social Justice and Empowerment.",
        ALL_STATE_CODES,
        ["POSTGRADUATE", "DOCTORAL"],
        ["ALL_RECOGNIZED_COURSES"],
        ["CENTRAL_GOVERNMENT", "SC", "OVERSEAS"],
        "https://nosmsje.gov.in/",
        "Applicants from eligible notified categories seeking specified overseas master's or doctoral study should verify age, income, qualification, university, and subject rules.",
    ),
    _scheme(
        "national-fellowship-scholarship-higher-education-st",
        "goi",
        "National Fellowship and Scholarship for Higher Education of ST Students",
        "Ministry of Tribal Affairs support for eligible ST students in higher education.",
        ALL_STATE_CODES,
        ["UNDERGRADUATE", "POSTGRADUATE", "DOCTORAL"],
        ["ALL_RECOGNIZED_COURSES"],
        ["CENTRAL_GOVERNMENT", "ST", "HIGHER_EDUCATION"],
        "https://tribal.nic.in/ScholarshiP.aspx",
        "ST students should check the current scholarship or fellowship component, institution, programme, income, and selection rules published by the Ministry.",
    ),
    _scheme(
        "national-overseas-scholarship-st-students",
        "goi",
        "National Overseas Scholarship for Scheduled Tribe Students",
        "Overseas postgraduate and research support administered by the Ministry of Tribal Affairs.",
        ALL_STATE_CODES,
        ["POSTGRADUATE", "DOCTORAL"],
        ["ALL_RECOGNIZED_COURSES"],
        ["CENTRAL_GOVERNMENT", "ST", "OVERSEAS"],
        "https://overseas.tribal.gov.in/",
        "Eligible ST applicants planning overseas higher study should verify age, income, qualification, university, course, and selection requirements.",
    ),
    _scheme(
        "top-class-education-students-with-disabilities",
        "goi",
        "Scholarships for Students with Disabilities — Top Class Education",
        "Central support for students with benchmark disabilities pursuing eligible higher education.",
        ALL_STATE_CODES,
        ["UNDERGRADUATE", "POSTGRADUATE"],
        ["ALL_RECOGNIZED_COURSES"],
        ["CENTRAL_GOVERNMENT", "DISABILITY", "TOP_CLASS_EDUCATION"],
        "https://depwd.gov.in/scholarship/",
        "Students meeting the notified disability benchmark and studying in an eligible institution should verify course, income, disability-document, and renewal rules.",
    ),
]


# Twenty schemes across twenty different State Governments.
STATE_SCHOLARSHIP_SPECS = [
    _scheme(
        "west-bengal-swami-vivekananda-merit-cum-means",
        "west_bengal",
        "Swami Vivekananda Merit-cum-Means Scholarship",
        "West Bengal merit-cum-means support across eligible levels of study.",
        ["WB"],
        ["CLASS_11_12", "UNDERGRADUATE", "POSTGRADUATE"],
        ["ALL_RECOGNIZED_COURSES"],
        ["STATE_GOVERNMENT", "WEST_BENGAL", "MERIT", "INCOME"],
        "https://svmcm.wb.gov.in/",
        "West Bengal students should verify examination marks, family income, course, institution, and renewal rules on the official SVMCM portal.",
    ),
    _scheme(
        "odisha-e-medhabruti-scholarship",
        "odisha_ref",
        "e-Medhabruti Scholarship",
        "Odisha merit scholarship for eligible undergraduate, postgraduate, technical, and professional learners.",
        ["OD"],
        ["UNDERGRADUATE", "POSTGRADUATE"],
        ["ALL_RECOGNIZED_COURSES"],
        ["STATE_GOVERNMENT", "ODISHA", "MERIT"],
        "https://scholarship.odisha.gov.in/",
        "Odisha-domiciled students should check the current merit, income, course, institution, and category conditions on the State Scholarship Portal.",
    ),
    _scheme(
        "gujarat-mukhyamantri-yuva-swavalamban-yojana",
        "gujarat",
        "Mukhyamantri Yuva Swavalamban Yojana",
        "Gujarat higher-education assistance commonly known as MYSY.",
        ["GJ"],
        ["DIPLOMA", "UNDERGRADUATE"],
        ["ALL_RECOGNIZED_COURSES"],
        ["STATE_GOVERNMENT", "GUJARAT", "MERIT", "INCOME"],
        "https://mysy.guj.nic.in/",
        "Gujarat students entering an eligible diploma or degree programme should verify board marks, admission route, income, course, and renewal rules.",
    ),
    _scheme(
        "maharashtra-rajarshi-shahu-maharaj-shikshan-shulkh-shishyavrutti",
        "maharashtra",
        "Rajarshi Chhatrapati Shahu Maharaj Shikshan Shulkh Shishyavrutti Scheme",
        "Maharashtra fee assistance available through the MahaDBT system.",
        ["MH"],
        ["DIPLOMA", "UNDERGRADUATE", "POSTGRADUATE"],
        ["ALL_RECOGNIZED_COURSES"],
        ["STATE_GOVERNMENT", "MAHARASHTRA", "FEE_ASSISTANCE"],
        "https://mahadbt.maharashtra.gov.in/",
        "Maharashtra students should verify domicile, admission category, income, course, attendance, and fee conditions on MahaDBT.",
    ),
    _scheme(
        "karnataka-ssp-post-matric-scholarship",
        "karnataka",
        "Karnataka SSP Post-Matric Scholarship",
        "Post-matric assistance delivered through Karnataka's State Scholarship Portal.",
        ["KA"],
        ["CLASS_11_12", "DIPLOMA", "UNDERGRADUATE", "POSTGRADUATE"],
        ["ALL_RECOGNIZED_COURSES"],
        ["STATE_GOVERNMENT", "KARNATAKA", "POST_MATRIC"],
        "https://ssp.postmatric.karnataka.gov.in/",
        "Karnataka students should verify department, community, income, study, e-attestation, and renewal requirements on SSP.",
    ),
    _scheme(
        "kerala-state-merit-scholarship",
        "kerala",
        "Kerala State Merit Scholarship",
        "Merit support for eligible higher-education students administered by Kerala.",
        ["KL"],
        ["UNDERGRADUATE", "POSTGRADUATE"],
        ["ALL_RECOGNIZED_COURSES"],
        ["STATE_GOVERNMENT", "KERALA", "MERIT"],
        "https://dcescholarship.kerala.gov.in/",
        "Kerala students should verify qualifying marks, income, programme, institution, and current application conditions with the Department of Collegiate Education.",
    ),
    _scheme(
        "tamil-nadu-bc-mbc-dnc-post-matric-scholarship",
        "tamil_nadu",
        "Tamil Nadu BC, MBC and DNC Post-Matric Scholarship",
        "Post-matric welfare support for eligible BC, MBC and DNC learners in Tamil Nadu.",
        ["TN"],
        ["CLASS_11_12", "DIPLOMA", "UNDERGRADUATE", "POSTGRADUATE"],
        ["ALL_RECOGNIZED_COURSES"],
        ["STATE_GOVERNMENT", "TAMIL_NADU", "BC", "MBC", "DNC"],
        "https://bcmbcmw.tn.gov.in/welfschemes.htm",
        "Eligible Tamil Nadu BC, MBC and DNC students should verify community, income, institution, course, and fee conditions in the current department notice.",
    ),
    _scheme(
        "telangana-epass-post-matric-scholarship",
        "telangana",
        "Telangana ePASS Post-Matric Scholarship",
        "Fee reimbursement and post-matric support managed through Telangana ePASS.",
        ["TS"],
        ["CLASS_11_12", "DIPLOMA", "UNDERGRADUATE", "POSTGRADUATE"],
        ["ALL_RECOGNIZED_COURSES"],
        ["STATE_GOVERNMENT", "TELANGANA", "POST_MATRIC"],
        "https://telanganaepass.cgg.gov.in/",
        "Telangana students should verify eligible welfare category, income, attendance, course, institution, and application route on ePASS.",
    ),
    _scheme(
        "andhra-pradesh-jnanabhumi-post-matric-scholarship",
        "andhra_pradesh",
        "Andhra Pradesh JnanaBhumi Post-Matric Scholarship",
        "Post-matric scholarship and fee-support services available through JnanaBhumi.",
        ["AP"],
        ["CLASS_11_12", "DIPLOMA", "UNDERGRADUATE", "POSTGRADUATE"],
        ["ALL_RECOGNIZED_COURSES"],
        ["STATE_GOVERNMENT", "ANDHRA_PRADESH", "POST_MATRIC"],
        "https://jnanabhumi.ap.gov.in/",
        "Andhra Pradesh students should verify social category, income, attendance, programme, institution, and current registration requirements on JnanaBhumi.",
    ),
    _scheme(
        "madhya-pradesh-mukhyamantri-medhavi-vidyarthi-yojana",
        "madhya_pradesh",
        "Mukhyamantri Medhavi Vidyarthi Yojana",
        "Madhya Pradesh higher-education support for eligible meritorious students.",
        ["MP"],
        ["UNDERGRADUATE"],
        ["ALL_UNDERGRADUATE"],
        ["STATE_GOVERNMENT", "MADHYA_PRADESH", "MERIT"],
        "https://hescholarship.mp.gov.in/",
        "Madhya Pradesh students should verify board or entrance performance, domicile, income, programme, institution, and fee-support conditions.",
    ),
    _scheme(
        "rajasthan-chief-minister-higher-education-scholarship",
        "rajasthan",
        "Rajasthan Chief Minister Higher Education Scholarship",
        "Rajasthan higher-education assistance for eligible students continuing after senior secondary school.",
        ["RJ"],
        ["UNDERGRADUATE"],
        ["ALL_UNDERGRADUATE"],
        ["STATE_GOVERNMENT", "RAJASTHAN", "MERIT", "INCOME"],
        "https://hte.rajasthan.gov.in/",
        "Rajasthan students should verify board merit, income, regular-study, course, and other scholarship conditions in the current Higher Education notice.",
    ),
    _scheme(
        "uttar-pradesh-post-matric-scholarship",
        "uttar_pradesh",
        "Uttar Pradesh Post-Matric Scholarship",
        "Post-matric scholarship support administered through the Uttar Pradesh scholarship portal.",
        ["UP"],
        ["CLASS_11_12", "DIPLOMA", "UNDERGRADUATE", "POSTGRADUATE"],
        ["ALL_RECOGNIZED_COURSES"],
        ["STATE_GOVERNMENT", "UTTAR_PRADESH", "POST_MATRIC"],
        "https://scholarship.up.gov.in/",
        "Uttar Pradesh students should verify category, income, domicile, course, institution, registration, and renewal rules on the official portal.",
    ),
    _scheme(
        "bihar-post-matric-scholarship",
        "bihar",
        "Bihar Post-Matric Scholarship",
        "Post-matric assistance for eligible Bihar students through the state PMS portal.",
        ["BR"],
        ["CLASS_11_12", "DIPLOMA", "UNDERGRADUATE", "POSTGRADUATE"],
        ["ALL_RECOGNIZED_COURSES"],
        ["STATE_GOVERNMENT", "BIHAR", "POST_MATRIC"],
        "https://www.pmsonline.bih.nic.in/",
        "Bihar students should verify the category currently open, domicile, income, course, institution, and academic-year notice on the PMS portal.",
    ),
    _scheme(
        "jharkhand-ekalyan-post-matric-scholarship",
        "jharkhand",
        "Jharkhand e-Kalyan Post-Matric Scholarship",
        "Post-matric welfare scholarship administered through Jharkhand e-Kalyan.",
        ["JH"],
        ["CLASS_11_12", "DIPLOMA", "UNDERGRADUATE", "POSTGRADUATE"],
        ["ALL_RECOGNIZED_COURSES"],
        ["STATE_GOVERNMENT", "JHARKHAND", "POST_MATRIC"],
        "https://ekalyan.cgg.gov.in/",
        "Jharkhand students should verify category, income, domicile, institution, course, and current application conditions on e-Kalyan.",
    ),
    _scheme(
        "haryana-har-chhatravratti-post-matric-scholarship",
        "haryana",
        "Haryana Har-Chhatravratti Post-Matric Scholarship",
        "Centralized Haryana scholarship support through the Har-Chhatravratti portal.",
        ["HR"],
        ["CLASS_11_12", "DIPLOMA", "UNDERGRADUATE", "POSTGRADUATE"],
        ["ALL_RECOGNIZED_COURSES"],
        ["STATE_GOVERNMENT", "HARYANA", "POST_MATRIC"],
        "https://harchhatravratti.highereduhry.ac.in/",
        "Haryana students should verify scheme, domicile, family income, category, attendance, programme, and Parivar Pehchan or portal requirements.",
    ),
    _scheme(
        "punjab-dr-ambedkar-post-matric-scholarship",
        "punjab",
        "Punjab Dr. Ambedkar Post-Matric Scholarship",
        "Punjab post-matric scholarship service for eligible welfare-category students.",
        ["PB"],
        ["CLASS_11_12", "DIPLOMA", "UNDERGRADUATE", "POSTGRADUATE"],
        ["ALL_RECOGNIZED_COURSES"],
        ["STATE_GOVERNMENT", "PUNJAB", "POST_MATRIC"],
        "https://scholarships.punjab.gov.in/",
        "Punjab students, including eligible students studying outside the state, should verify category, income, course, institution, and current portal conditions.",
    ),
    _scheme(
        "himachal-pradesh-kalpana-chawla-chhatravriti",
        "himachal_pradesh",
        "Kalpana Chawla Chhatravriti Yojana",
        "Himachal Pradesh merit scholarship supporting eligible girl students after Class 12.",
        ["HP"],
        ["UNDERGRADUATE"],
        ["ALL_UNDERGRADUATE"],
        ["STATE_GOVERNMENT", "HIMACHAL_PRADESH", "WOMEN", "MERIT"],
        "https://hpepass.cgg.gov.in/",
        "Girl students from Himachal Pradesh should verify Class 12 merit, board, course, institution, and current selection conditions on HP ePASS.",
    ),
    _scheme(
        "assam-combined-merit-degree-scholarship",
        "assam",
        "Assam Combined Merit Degree Scholarship",
        "Assam merit assistance for eligible undergraduate and postgraduate students.",
        ["AS"],
        ["UNDERGRADUATE", "POSTGRADUATE"],
        ["ALL_RECOGNIZED_COURSES"],
        ["STATE_GOVERNMENT", "ASSAM", "MERIT"],
        "https://directorateofhighereducation.assam.gov.in/",
        "Assam students should verify qualifying marks, domicile, regular programme, institution, bank, and current application conditions with DHE Assam.",
    ),
    _scheme(
        "uttarakhand-post-matric-scholarship",
        "uttarakhand",
        "Uttarakhand Post-Matric Scholarship",
        "Post-matric welfare support for eligible Uttarakhand students.",
        ["UK"],
        ["CLASS_11_12", "DIPLOMA", "UNDERGRADUATE", "POSTGRADUATE"],
        ["ALL_RECOGNIZED_COURSES"],
        ["STATE_GOVERNMENT", "UTTARAKHAND", "POST_MATRIC"],
        "https://escholarship.uk.gov.in/",
        "Uttarakhand students should verify category, domicile, income, institution, course, and current state portal requirements.",
    ),
    _scheme(
        "chhattisgarh-post-matric-scholarship",
        "chhattisgarh",
        "Chhattisgarh Post-Matric Scholarship",
        "Post-matric assistance for eligible Chhattisgarh learners.",
        ["CG"],
        ["CLASS_11_12", "DIPLOMA", "UNDERGRADUATE", "POSTGRADUATE"],
        ["ALL_RECOGNIZED_COURSES"],
        ["STATE_GOVERNMENT", "CHHATTISGARH", "POST_MATRIC"],
        "https://postmatric-scholarship.cg.nic.in/",
        "Chhattisgarh students should verify category, income, domicile, course, institution, and the current application notice on the official portal.",
    ),
]


# Ten active, recognizable private-company or NGO programmes with provider/source links.
PRIVATE_NGO_SCHOLARSHIP_SPECS = [
    _scheme(
        "reliance-foundation-undergraduate-scholarships",
        "reliance_foundation",
        "Reliance Foundation Undergraduate Scholarships",
        "Merit-cum-means support for first-year full-time undergraduate students across India.",
        ALL_STATE_CODES,
        ["UNDERGRADUATE"],
        ["ALL_UNDERGRADUATE"],
        ["NGO", "MERIT", "INCOME"],
        "https://scholarships.reliancefoundation.org/UG_Scholarship.aspx",
        "First-year full-time undergraduate students should verify household income, aptitude assessment, academic, and application conditions for the current cycle.",
        "Selected scholars may receive multi-year financial support and development opportunities according to the current programme rules.",
    ),
    _scheme(
        "reliance-foundation-postgraduate-scholarships",
        "reliance_foundation",
        "Reliance Foundation Postgraduate Scholarships",
        "Postgraduate support for selected students in future-facing fields of study.",
        ALL_STATE_CODES,
        ["POSTGRADUATE"],
        ["STEM"],
        ["NGO", "POSTGRADUATE", "STEM"],
        "https://scholarships.reliancefoundation.org/PG_Scholarship.aspx",
        "First-year postgraduate students in eligible future-ready disciplines should verify programme, merit, aptitude, and selection requirements.",
        "Selected scholars may receive financial support, mentoring, and development opportunities under the current programme.",
    ),
    _scheme(
        "sbi-platinum-jubilee-asha-scholarship",
        "sbi_foundation",
        "SBI Platinum Jubilee Asha Scholarship",
        "SBI Foundation education support spanning school and higher-education categories.",
        ALL_STATE_CODES,
        ["CLASS_9_12", "UNDERGRADUATE", "POSTGRADUATE"],
        ["ALL_RECOGNIZED_COURSES"],
        ["NGO", "MERIT", "INCOME"],
        "https://www.ashascholarship.org/",
        "Students should select the correct school, undergraduate, postgraduate, medical, IIT, IIM, or overseas category and verify marks, income, institution, and renewal conditions.",
        "Award value depends on the selected education category and current official programme rules.",
    ),
    _scheme(
        "hdfc-bank-parivartan-ecss-programme",
        "hdfc_bank",
        "HDFC Bank Parivartan Educational Crisis Scholarship Support Programme",
        "Need-based support for students facing personal or family financial crisis.",
        ALL_STATE_CODES,
        ["SCHOOL", "DIPLOMA", "UNDERGRADUATE", "POSTGRADUATE"],
        ["ALL_RECOGNIZED_COURSES"],
        ["PRIVATE_COMPANY", "CRISIS_SUPPORT", "INCOME"],
        "https://www.hdfcbank.com/personal/about-us/corporate-social-responsibility/parivartan",
        "Students experiencing a documented financial or personal crisis should verify academic, income, course, and crisis-evidence requirements for the current programme.",
    ),
    _scheme(
        "kotak-kanya-scholarship",
        "kotak_foundation",
        "Kotak Kanya Scholarship",
        "Higher-education support for meritorious girls from underserved backgrounds.",
        ALL_STATE_CODES,
        ["UNDERGRADUATE"],
        ["PROFESSIONAL_COURSES"],
        ["NGO", "WOMEN", "MERIT", "INCOME"],
        "https://kotakeducation.org/kotak-kanya-scholarship/",
        "Girl students entering an eligible professional undergraduate programme should verify marks, income, institution, course, and continuation conditions.",
    ),
    _scheme(
        "tata-capital-pankh-scholarship-programme",
        "tata_capital",
        "Tata Capital Pankh Scholarship Programme",
        "Education support for meritorious students from economically underprivileged backgrounds.",
        ALL_STATE_CODES,
        ["CLASS_11_12", "DIPLOMA", "UNDERGRADUATE"],
        ["ALL_RECOGNIZED_COURSES"],
        ["PRIVATE_COMPANY", "MERIT", "INCOME"],
        "https://www.tata.com/newsroom/community/tata-capital-pankh-scholarship",
        "Students should verify the currently offered class, diploma, general-graduation, or professional-course category plus marks, income, and fee conditions.",
    ),
    _scheme(
        "santoor-womens-scholarship",
        "wipro_cares",
        "Santoor Women's Scholarship",
        "Higher-education support for girls from disadvantaged backgrounds after Class 12.",
        ["AP", "KA", "TS", "CG"],
        ["UNDERGRADUATE"],
        ["ALL_UNDERGRADUATE"],
        ["NGO", "WOMEN", "INCOME"],
        "https://santoorscholarships.com/",
        "Young women from the states covered in the current cycle should verify government-school, Class 12, undergraduate admission, and background conditions.",
    ),
    _scheme(
        "foundation-for-excellence-scholarship",
        "ffe",
        "Foundation For Excellence Scholarship",
        "Scholarship and mentoring support for academically strong students in selected professional courses.",
        ALL_STATE_CODES,
        ["UNDERGRADUATE"],
        ["BTECH", "BE", "MBBS", "LAW"],
        ["NGO", "MERIT", "INCOME", "PROFESSIONAL_COURSES"],
        "https://ffe.org/scholarships/",
        "Students entering an eligible engineering, medical, law, or other currently supported professional course should verify entrance rank, income, marks, and programme conditions.",
    ),
    _scheme(
        "colgate-keep-india-smiling-foundation-scholarship",
        "colgate",
        "Colgate Keep India Smiling Foundation Scholarship",
        "Foundational education support for deserving and meritorious students with limited resources.",
        ALL_STATE_CODES,
        ["UNDERGRADUATE", "POSTGRADUATE"],
        ["BDS", "MDS", "STEM"],
        ["PRIVATE_COMPANY", "MERIT", "INCOME"],
        "https://www.colgate.com/en-in/smile-karo-aur-shuru-ho-jao/foundation-scholarship",
        "Students should verify the active course category, marks, income, institution, and one-time or renewal terms on Colgate's current programme page.",
    ),
    _scheme(
        "loreal-india-for-young-women-in-science-scholarship",
        "loreal",
        "L'Oréal India For Young Women in Science Scholarship",
        "Science-education support for young women from economically constrained backgrounds.",
        ALL_STATE_CODES,
        ["UNDERGRADUATE"],
        ["STEM", "MEDICAL"],
        ["PRIVATE_COMPANY", "WOMEN", "SCIENCE", "INCOME"],
        "https://www.loreal.com/en/india/pages/commitments/for-young-women-in-science/",
        "Young women entering an eligible science-related undergraduate programme should verify Class 12 stream, marks, income, age, course, and admission conditions.",
    ),
]

REFERENCE_SCHOLARSHIP_SPECS = [
    *CENTRAL_SCHOLARSHIP_SPECS,
    *STATE_SCHOLARSHIP_SPECS,
    *PRIVATE_NGO_SCHOLARSHIP_SPECS,
]

assert len(CENTRAL_SCHOLARSHIP_SPECS) == 20
assert len(STATE_SCHOLARSHIP_SPECS) == 20
assert len(PRIVATE_NGO_SCHOLARSHIP_SPECS) == 10
assert len(REFERENCE_SCHOLARSHIP_SPECS) == 50
assert len({spec["slug"] for spec in REFERENCE_SCHOLARSHIP_SPECS}) == 50
assert len({spec["states"][0] for spec in STATE_SCHOLARSHIP_SPECS}) == 20
assert all(len(spec["states"]) == 1 for spec in STATE_SCHOLARSHIP_SPECS)
assert all(
    spec["official_source_url"].startswith("https://") for spec in REFERENCE_SCHOLARSHIP_SPECS
)
assert {spec["organization"] for spec in REFERENCE_SCHOLARSHIP_SPECS} <= {
    spec["key"] for spec in REFERENCE_ORGANIZATION_SPECS
}
