from __future__ import annotations

from typing import Any

from app.models import OrganizationType

ALL_STATE_CODES = ["ALL"]

REGISTRATION_WINDOWS = (
    ("2026-07-01T09:00:00+00:00", "2026-10-15T23:59:00+00:00"),
    ("2026-07-15T09:00:00+00:00", "2026-10-31T23:59:00+00:00"),
    ("2026-08-01T09:00:00+00:00", "2026-11-15T23:59:00+00:00"),
    ("2026-08-10T09:00:00+00:00", "2026-11-30T23:59:00+00:00"),
    ("2026-08-20T09:00:00+00:00", "2026-12-15T23:59:00+00:00"),
    ("2026-09-01T09:00:00+00:00", "2026-12-31T23:59:00+00:00"),
)


def _organization(
    key: str,
    display_name: str,
    organization_type: OrganizationType,
    state: str | None = None,
) -> dict[str, Any]:
    return {
        "key": key,
        "slug": display_name.lower().replace("&", "and").replace("'", "").replace(" ", "-"),
        "legal_name": display_name,
        "display_name": display_name,
        "type": organization_type,
        "state": state,
        "publisher_login": f"publisher.{key}@scholarsaathi.local",
    }


CATALOG_ORGANIZATION_SPECS = [
    _organization(
        "central",
        "National Education Scholarship Directorate",
        OrganizationType.CENTRAL_GOVERNMENT,
    ),
    _organization(
        "odisha",
        "Odisha Student Opportunity Mission",
        OrganizationType.STATE_GOVERNMENT,
        "OD",
    ),
    _organization(
        "aarohan",
        "Aarohan Future Skills",
        OrganizationType.PRIVATE_COMPANY,
    ),
    _organization("udaan", "Udaan Learning Trust", OrganizationType.NGO),
    _organization(
        "goi",
        "National Scholarship Mission",
        OrganizationType.CENTRAL_GOVERNMENT,
    ),
    _organization(
        "west_bengal",
        "West Bengal Scholarship Directorate",
        OrganizationType.STATE_GOVERNMENT,
        "WB",
    ),
    _organization(
        "odisha_ref",
        "Odisha Higher Education Scholarship Board",
        OrganizationType.STATE_GOVERNMENT,
        "OD",
    ),
    _organization(
        "gujarat",
        "Gujarat Student Support Directorate",
        OrganizationType.STATE_GOVERNMENT,
        "GJ",
    ),
    _organization(
        "maharashtra",
        "Maharashtra Education Benefit Authority",
        OrganizationType.STATE_GOVERNMENT,
        "MH",
    ),
    _organization(
        "karnataka",
        "Karnataka Scholarship Services",
        OrganizationType.STATE_GOVERNMENT,
        "KA",
    ),
    _organization(
        "kerala",
        "Kerala Collegiate Scholarship Directorate",
        OrganizationType.STATE_GOVERNMENT,
        "KL",
    ),
    _organization(
        "tamil_nadu",
        "Tamil Nadu Student Welfare Directorate",
        OrganizationType.STATE_GOVERNMENT,
        "TN",
    ),
    _organization(
        "telangana",
        "Telangana Education Assistance Board",
        OrganizationType.STATE_GOVERNMENT,
        "TS",
    ),
    _organization(
        "andhra_pradesh",
        "Andhra Pradesh Student Benefit Authority",
        OrganizationType.STATE_GOVERNMENT,
        "AP",
    ),
    _organization(
        "madhya_pradesh",
        "Madhya Pradesh Higher Education Mission",
        OrganizationType.STATE_GOVERNMENT,
        "MP",
    ),
    _organization(
        "rajasthan",
        "Rajasthan Scholarship Directorate",
        OrganizationType.STATE_GOVERNMENT,
        "RJ",
    ),
    _organization(
        "uttar_pradesh",
        "Uttar Pradesh Student Scholarship Board",
        OrganizationType.STATE_GOVERNMENT,
        "UP",
    ),
    _organization(
        "bihar",
        "Bihar Post-Matric Support Directorate",
        OrganizationType.STATE_GOVERNMENT,
        "BR",
    ),
    _organization(
        "jharkhand",
        "Jharkhand Student Welfare Mission",
        OrganizationType.STATE_GOVERNMENT,
        "JH",
    ),
    _organization(
        "haryana",
        "Haryana Higher Education Scholarship Cell",
        OrganizationType.STATE_GOVERNMENT,
        "HR",
    ),
    _organization(
        "punjab",
        "Punjab Student Opportunity Directorate",
        OrganizationType.STATE_GOVERNMENT,
        "PB",
    ),
    _organization(
        "himachal_pradesh",
        "Himachal Pradesh Merit Scholarship Board",
        OrganizationType.STATE_GOVERNMENT,
        "HP",
    ),
    _organization(
        "assam",
        "Assam Higher Education Support Mission",
        OrganizationType.STATE_GOVERNMENT,
        "AS",
    ),
    _organization(
        "uttarakhand",
        "Uttarakhand Student Assistance Directorate",
        OrganizationType.STATE_GOVERNMENT,
        "UK",
    ),
    _organization(
        "chhattisgarh",
        "Chhattisgarh Education Support Board",
        OrganizationType.STATE_GOVERNMENT,
        "CG",
    ),
    _organization(
        "reliance_foundation",
        "Pragati Education Foundation",
        OrganizationType.NGO,
    ),
    _organization(
        "sbi_foundation",
        "Asha Scholars Foundation",
        OrganizationType.NGO,
    ),
    _organization(
        "hdfc_bank",
        "NavPragati Education Trust",
        OrganizationType.PRIVATE_COMPANY,
    ),
    _organization(
        "kotak_foundation",
        "Kanya Shiksha Foundation",
        OrganizationType.NGO,
    ),
    _organization(
        "tata_capital",
        "Pankh Learning Initiative",
        OrganizationType.PRIVATE_COMPANY,
    ),
    _organization("wipro_cares", "Santoor Education Trust", OrganizationType.NGO),
    _organization("ffe", "Excellence Scholars Foundation", OrganizationType.NGO),
    _organization(
        "colgate",
        "Ujjwal Smiles Education Initiative",
        OrganizationType.PRIVATE_COMPANY,
    ),
    _organization(
        "loreal",
        "Young Women in Science Foundation",
        OrganizationType.PRIVATE_COMPANY,
    ),
]

_ORGANIZATION_BY_KEY = {spec["key"]: spec for spec in CATALOG_ORGANIZATION_SPECS}


def _document_requirements(
    states: list[str],
    levels: list[str],
    tags: list[str],
) -> list[str]:
    documents = ["CURRENT_MARKSHEET", "INCOME_CERTIFICATE"]
    if any(level in {"CLASS_9_10", "CLASS_9_12"} for level in levels):
        documents.append("CLASS_10_MARKSHEET")
    if any(level in {"CLASS_11_12", "UNDERGRADUATE"} for level in levels):
        documents.append("CLASS_12_MARKSHEET")
    if states != ALL_STATE_CODES:
        documents.append("DOMICILE_CERTIFICATE")
    if set(tags) & {"SC", "ST", "OBC", "EBC", "DNT", "MINORITY"}:
        documents.append("CATEGORY_CERTIFICATE")
    if "DISABILITY" in tags:
        documents.append("DISABILITY_CERTIFICATE")
    return list(dict.fromkeys(documents))


def _scheme(
    slug: str,
    organization: str,
    title: str,
    summary: str,
    states: list[str],
    levels: list[str],
    courses: list[str],
    tags: list[str],
    minimum_marks: int,
    maximum_income: int,
    award: tuple[int, int],
    window: int,
) -> dict[str, Any]:
    opens_at, deadline_at = REGISTRATION_WINDOWS[window % len(REGISTRATION_WINDOWS)]
    organization_type = _ORGANIZATION_BY_KEY[organization]["type"]
    if states != ALL_STATE_CODES and len(states) > 1:
        scope = "REGIONAL"
    elif organization_type == OrganizationType.CENTRAL_GOVERNMENT:
        scope = "NATIONAL"
    elif organization_type == OrganizationType.STATE_GOVERNMENT:
        scope = "STATE"
    elif organization_type == OrganizationType.PRIVATE_COMPANY:
        scope = "NATIONAL_PRIVATE"
    else:
        scope = "NATIONAL_NGO"

    eligible_categories = [
        value for value in ("SC", "ST", "OBC", "EBC", "DNT", "MINORITY") if value in tags
    ] or ["ALL"]
    eligible_genders = ["FEMALE"] if "WOMEN" in tags else ["ALL"]
    required_documents = _document_requirements(states, levels, tags)
    state_text = "all States and Union Territories" if states == ALL_STATE_CODES else states[0]
    course_text = ", ".join(course.replace("_", " ").title() for course in courses)
    level_text = ", ".join(level.replace("_", " ").title() for level in levels)
    amount_min, amount_max = award
    eligibility = (
        f"Indian students studying at {level_text} level in {course_text} may apply. "
        f"Coverage is {state_text}. Applicants need at least {minimum_marks}% in the "
        f"most recent qualifying examination and annual household income must not exceed "
        f"₹{maximum_income:,}. Category, gender, disability, domicile and course-year "
        "conditions apply only where listed in the structured rules."
    )
    benefit = (
        f"Selected students receive ₹{amount_min:,} to ₹{amount_max:,} for tuition, "
        "books, learning equipment and other approved academic expenses during 2026–27."
    )
    application_steps = [
        "Complete or confirm the reusable student profile.",
        "Upload every document listed for the scheme.",
        "Ask the ScholarSaathi agent to check eligibility and prepare the application.",
        "Review the completed form and explicitly authorize submission.",
        "Track verification, correction requests and the final decision in the application timeline.",
    ]
    selection_steps = [
        "Applications are screened for completeness and rule compliance.",
        "Eligible applications are ranked using academic merit and household need.",
        "The provider review team records the final decision and any correction request.",
        "Renewal requires continued enrolment and satisfactory academic progress.",
    ]
    document_rules = [
        {
            "document_type": document_type,
            "required": True,
            "condition": "ALWAYS",
        }
        for document_type in required_documents
    ]
    return {
        "slug": slug,
        "organization": organization,
        "title": title,
        "summary": summary,
        "academic_year": "2026-27",
        "scope": scope,
        "states": list(states),
        "levels": list(levels),
        "courses": list(courses),
        "tags": list(tags),
        "benefit": benefit,
        "amount_min": amount_min,
        "amount_max": amount_max,
        "opens_at": opens_at,
        "deadline_at": deadline_at,
        "eligibility": eligibility,
        "required_documents": required_documents,
        "document_rules": document_rules,
        "application_steps": application_steps,
        "selection_steps": selection_steps,
        "eligibility_rules": {
            "nationality": {"operator": "EQUALS", "value": "INDIAN"},
            "state_codes": {
                "operator": "ALL_INDIA" if states == ALL_STATE_CODES else "IN",
                "values": list(states),
            },
            "education_levels": {"operator": "IN", "values": list(levels)},
            "course_families": {"operator": "IN", "values": list(courses)},
            "minimum_marks_percentage": minimum_marks,
            "maximum_family_income": maximum_income,
            "eligible_categories": eligible_categories,
            "eligible_genders": eligible_genders,
            "requires_disability": "DISABILITY" in tags,
            "eligible_course_years": [1, 2, 3, 4, 5],
        },
        "application_process": {
            "mode": "SCHOLARSAATHI_AGENT",
            "registration_opens_at": opens_at,
            "registration_deadline_at": deadline_at,
            "steps": application_steps,
            "selection_steps": selection_steps,
            "correction_window_enabled": True,
            "student_confirmation_required": True,
        },
        "official_source_url": f"/scheme-guidelines/{slug}",
        "provider_helpdesk_url": f"/scheme-helpdesk/{slug}",
    }


ORIGINAL_SCHOLARSHIP_SPECS = [
    _scheme(
        "national-technical-learner-grant-2026",
        "central",
        "National Technical Learner Grant 2026–27",
        "Annual academic support for diploma and undergraduate technical learners across India.",
        ALL_STATE_CODES,
        ["DIPLOMA", "UNDERGRADUATE"],
        ["BTECH", "BE", "TECHNICAL_DIPLOMA"],
        ["MERIT", "INCOME", "TECHNICAL_EDUCATION"],
        65,
        800000,
        (50000, 75000),
        1,
    ),
    _scheme(
        "national-higher-education-access-award-2026",
        "central",
        "National Higher Education Access Award 2026–27",
        "Merit-and-means assistance for students beginning a recognized undergraduate programme.",
        ALL_STATE_CODES,
        ["UNDERGRADUATE"],
        ["ALL_UNDERGRADUATE"],
        ["FIRST_YEAR", "MERIT", "INCOME"],
        75,
        450000,
        (40000, 50000),
        2,
    ),
    _scheme(
        "odisha-technical-pathways-scholarship-2026",
        "odisha",
        "Odisha Technical Pathways Scholarship 2026–27",
        "State support for Odisha students pursuing technical degrees and diplomas.",
        ["OD"],
        ["DIPLOMA", "UNDERGRADUATE"],
        ["BTECH", "BE", "BARCH", "TECHNICAL_DIPLOMA"],
        ["ODISHA", "INCOME", "TECHNICAL_EDUCATION"],
        60,
        300000,
        (55000, 55000),
        0,
    ),
    _scheme(
        "odisha-rural-women-stem-fellowship-2026",
        "odisha",
        "Odisha Rural Women in STEM Fellowship 2026–27",
        "Academic and mentoring support for women from rural Odisha studying STEM subjects.",
        ["OD"],
        ["UNDERGRADUATE", "POSTGRADUATE"],
        ["STEM"],
        ["WOMEN", "RURAL", "ODISHA", "STEM"],
        60,
        500000,
        (60000, 60000),
        3,
    ),
    _scheme(
        "aarohan-women-engineers-scholarship-2026",
        "aarohan",
        "Aarohan Women Engineers Scholarship 2026–27",
        "Tuition and mentoring support for women pursuing engineering degrees.",
        ALL_STATE_CODES,
        ["UNDERGRADUATE"],
        ["BTECH", "BE"],
        ["WOMEN", "ENGINEERING", "MERIT", "INCOME"],
        70,
        600000,
        (75000, 100000),
        1,
    ),
    _scheme(
        "aarohan-green-innovation-grant-2026",
        "aarohan",
        "Aarohan Green Innovation Student Grant 2026",
        "Project funding for final-year STEM students developing measurable sustainability solutions.",
        ALL_STATE_CODES,
        ["UNDERGRADUATE", "POSTGRADUATE"],
        ["STEM"],
        ["FINAL_YEAR", "PROJECT_GRANT", "SUSTAINABILITY"],
        65,
        800000,
        (50000, 150000),
        4,
    ),
    _scheme(
        "udaan-first-generation-graduate-fellowship-2026",
        "udaan",
        "Udaan First-Generation Graduate Fellowship 2026–27",
        "Scholarship and mentoring for first-generation undergraduate students.",
        ALL_STATE_CODES,
        ["UNDERGRADUATE"],
        ["ALL_UNDERGRADUATE"],
        ["FIRST_GENERATION", "INCOME", "MENTORING"],
        55,
        400000,
        (40000, 40000),
        0,
    ),
    _scheme(
        "udaan-accessible-education-scholarship-2026",
        "udaan",
        "Udaan Accessible Education Scholarship 2026–27",
        "Flexible study support for diploma and degree students with disabilities.",
        ALL_STATE_CODES,
        ["DIPLOMA", "UNDERGRADUATE", "POSTGRADUATE"],
        ["ALL_RECOGNIZED_COURSES"],
        ["DISABILITY", "ACCESSIBILITY", "INCOME"],
        50,
        800000,
        (40000, 80000),
        3,
    ),
]


CENTRAL_SCHOLARSHIP_SPECS = [
    _scheme(
        "national-merit-means-scholarship-2026",
        "goi",
        "National Merit and Means Scholarship 2026–27",
        "Academic support for high-performing students from lower-income households.",
        ALL_STATE_CODES,
        ["CLASS_11_12", "UNDERGRADUATE"],
        ["ALL_RECOGNIZED_COURSES"],
        ["CENTRAL_GOVERNMENT", "MERIT", "INCOME"],
        70,
        600000,
        (30000, 60000),
        0,
    ),
    _scheme(
        "national-technical-education-scholarship-2026",
        "goi",
        "National Technical Education Scholarship 2026–27",
        "Support for students in approved engineering and technical programmes.",
        ALL_STATE_CODES,
        ["DIPLOMA", "UNDERGRADUATE"],
        ["BTECH", "BE", "TECHNICAL_DIPLOMA"],
        ["CENTRAL_GOVERNMENT", "TECHNICAL_EDUCATION", "MERIT"],
        65,
        800000,
        (50000, 90000),
        1,
    ),
    _scheme(
        "national-women-stem-scholarship-2026",
        "goi",
        "National Women in STEM Scholarship 2026–27",
        "Higher-education support for women pursuing science and technology programmes.",
        ALL_STATE_CODES,
        ["UNDERGRADUATE", "POSTGRADUATE"],
        ["STEM", "BTECH", "BE"],
        ["CENTRAL_GOVERNMENT", "WOMEN", "STEM"],
        65,
        800000,
        (60000, 100000),
        2,
    ),
    _scheme(
        "national-school-continuation-award-2026",
        "goi",
        "National School Continuation Award 2026–27",
        "Financial support helping school learners continue through the secondary stage.",
        ALL_STATE_CODES,
        ["CLASS_9_12"],
        ["SCHOOL_EDUCATION"],
        ["CENTRAL_GOVERNMENT", "SCHOOL", "INCOME"],
        55,
        350000,
        (12000, 24000),
        3,
    ),
    _scheme(
        "national-post-matric-opportunity-scholarship-2026",
        "goi",
        "National Post-Matric Opportunity Scholarship 2026–27",
        "Post-matric assistance across recognized academic and vocational courses.",
        ALL_STATE_CODES,
        ["CLASS_11_12", "DIPLOMA", "UNDERGRADUATE"],
        ["ALL_RECOGNIZED_COURSES"],
        ["CENTRAL_GOVERNMENT", "POST_MATRIC", "INCOME"],
        55,
        500000,
        (25000, 65000),
        4,
    ),
    _scheme(
        "national-disability-education-support-2026",
        "goi",
        "National Accessible Education Support Scheme 2026–27",
        "Academic and accessibility assistance for students with disabilities.",
        ALL_STATE_CODES,
        ["CLASS_11_12", "DIPLOMA", "UNDERGRADUATE", "POSTGRADUATE"],
        ["ALL_RECOGNIZED_COURSES"],
        ["CENTRAL_GOVERNMENT", "DISABILITY", "ACCESSIBILITY"],
        50,
        800000,
        (40000, 100000),
        5,
    ),
    _scheme(
        "national-rural-learner-scholarship-2026",
        "goi",
        "National Rural Learner Scholarship 2026–27",
        "Merit-cum-means support for learners from rural communities.",
        ALL_STATE_CODES,
        ["CLASS_11_12", "UNDERGRADUATE"],
        ["ALL_RECOGNIZED_COURSES"],
        ["CENTRAL_GOVERNMENT", "RURAL", "MERIT", "INCOME"],
        60,
        500000,
        (30000, 70000),
        0,
    ),
    _scheme(
        "national-research-entry-fellowship-2026",
        "goi",
        "National Research Entry Fellowship 2026–27",
        "Fellowship support for postgraduate students beginning research-oriented study.",
        ALL_STATE_CODES,
        ["POSTGRADUATE", "DOCTORAL"],
        ["STEM", "SOCIAL_SCIENCES", "HUMANITIES"],
        ["CENTRAL_GOVERNMENT", "RESEARCH", "MERIT"],
        70,
        1000000,
        (90000, 150000),
        1,
    ),
    _scheme(
        "national-healthcare-education-scholarship-2026",
        "goi",
        "National Healthcare Education Scholarship 2026–27",
        "Support for students in medicine, nursing and allied health programmes.",
        ALL_STATE_CODES,
        ["UNDERGRADUATE", "POSTGRADUATE"],
        ["MBBS", "BDS", "NURSING", "ALLIED_HEALTH"],
        ["CENTRAL_GOVERNMENT", "HEALTHCARE", "MERIT"],
        70,
        800000,
        (75000, 125000),
        2,
    ),
    _scheme(
        "national-teacher-education-scholarship-2026",
        "goi",
        "National Teacher Education Scholarship 2026–27",
        "Financial assistance for students preparing for teaching careers.",
        ALL_STATE_CODES,
        ["UNDERGRADUATE", "POSTGRADUATE"],
        ["BED", "MED", "INTEGRATED_TEACHER_EDUCATION"],
        ["CENTRAL_GOVERNMENT", "TEACHER_EDUCATION", "INCOME"],
        60,
        600000,
        (40000, 70000),
        3,
    ),
    _scheme(
        "national-digital-skills-scholarship-2026",
        "goi",
        "National Digital Skills Scholarship 2026–27",
        "Support for degree and diploma learners in computing and digital technologies.",
        ALL_STATE_CODES,
        ["DIPLOMA", "UNDERGRADUATE", "POSTGRADUATE"],
        ["COMPUTER_SCIENCE", "IT", "DATA_SCIENCE", "BCA", "MCA"],
        ["CENTRAL_GOVERNMENT", "DIGITAL_SKILLS", "MERIT"],
        65,
        800000,
        (45000, 90000),
        4,
    ),
    _scheme(
        "national-sports-academics-scholarship-2026",
        "goi",
        "National Sports and Academics Scholarship 2026–27",
        "Education support for students balancing recognized sport and formal study.",
        ALL_STATE_CODES,
        ["CLASS_11_12", "UNDERGRADUATE"],
        ["ALL_RECOGNIZED_COURSES"],
        ["CENTRAL_GOVERNMENT", "SPORTS", "MERIT"],
        55,
        800000,
        (35000, 80000),
        5,
    ),
    _scheme(
        "national-arts-humanities-scholarship-2026",
        "goi",
        "National Arts and Humanities Scholarship 2026–27",
        "Merit support for students in arts, languages and humanities programmes.",
        ALL_STATE_CODES,
        ["UNDERGRADUATE", "POSTGRADUATE"],
        ["ARTS", "HUMANITIES", "LANGUAGES"],
        ["CENTRAL_GOVERNMENT", "ARTS", "MERIT"],
        65,
        700000,
        (35000, 70000),
        0,
    ),
    _scheme(
        "national-single-girl-child-scholarship-2026",
        "goi",
        "National Single Girl Child Scholarship 2026–27",
        "Higher-education support for eligible single girl children.",
        ALL_STATE_CODES,
        ["UNDERGRADUATE", "POSTGRADUATE"],
        ["ALL_RECOGNIZED_COURSES"],
        ["CENTRAL_GOVERNMENT", "WOMEN", "SINGLE_GIRL_CHILD"],
        60,
        800000,
        (50000, 85000),
        1,
    ),
    _scheme(
        "national-defence-families-scholarship-2026",
        "goi",
        "National Defence Families Scholarship 2026–27",
        "Professional-course assistance for eligible dependants of defence and security personnel.",
        ALL_STATE_CODES,
        ["UNDERGRADUATE", "POSTGRADUATE"],
        ["PROFESSIONAL_COURSES"],
        ["CENTRAL_GOVERNMENT", "DEFENCE_FAMILIES", "MERIT"],
        60,
        1000000,
        (60000, 100000),
        2,
    ),
    _scheme(
        "national-north-east-higher-education-scholarship-2026",
        "goi",
        "National North East Higher Education Scholarship 2026–27",
        "Undergraduate support for students from the North Eastern region.",
        ["AR", "AS", "MN", "ML", "MZ", "NL", "SK", "TR"],
        ["UNDERGRADUATE"],
        ["ALL_UNDERGRADUATE"],
        ["CENTRAL_GOVERNMENT", "NORTH_EAST", "MERIT"],
        60,
        800000,
        (50000, 80000),
        3,
    ),
    _scheme(
        "national-agriculture-education-scholarship-2026",
        "goi",
        "National Agriculture Education Scholarship 2026–27",
        "Support for students in agriculture and allied disciplines.",
        ALL_STATE_CODES,
        ["UNDERGRADUATE", "POSTGRADUATE"],
        ["AGRICULTURE", "HORTICULTURE", "VETERINARY", "FISHERIES"],
        ["CENTRAL_GOVERNMENT", "AGRICULTURE", "RURAL"],
        60,
        700000,
        (50000, 90000),
        4,
    ),
    _scheme(
        "national-law-studies-scholarship-2026",
        "goi",
        "National Law Studies Scholarship 2026–27",
        "Merit-cum-means support for students in recognized law programmes.",
        ALL_STATE_CODES,
        ["UNDERGRADUATE", "POSTGRADUATE"],
        ["LAW", "LLB", "LLM"],
        ["CENTRAL_GOVERNMENT", "LAW", "MERIT", "INCOME"],
        65,
        700000,
        (50000, 90000),
        5,
    ),
    _scheme(
        "national-diploma-advancement-scholarship-2026",
        "goi",
        "National Diploma Advancement Scholarship 2026–27",
        "Academic assistance for students in recognized diploma programmes.",
        ALL_STATE_CODES,
        ["DIPLOMA"],
        ["TECHNICAL_DIPLOMA", "VOCATIONAL_DIPLOMA"],
        ["CENTRAL_GOVERNMENT", "DIPLOMA", "INCOME"],
        55,
        500000,
        (25000, 50000),
        0,
    ),
    _scheme(
        "national-first-generation-graduate-scholarship-2026",
        "goi",
        "National First-Generation Graduate Scholarship 2026–27",
        "Support for students who are first in their immediate family to enter higher education.",
        ALL_STATE_CODES,
        ["UNDERGRADUATE"],
        ["ALL_UNDERGRADUATE"],
        ["CENTRAL_GOVERNMENT", "FIRST_GENERATION", "INCOME"],
        60,
        500000,
        (45000, 75000),
        1,
    ),
]


STATE_SCHOLARSHIP_SPECS = [
    _scheme(
        "west-bengal-merit-means-scholarship-2026",
        "west_bengal",
        "West Bengal Merit-cum-Means Scholarship 2026–27",
        "Merit-and-income-based support for West Bengal students.",
        ["WB"],
        ["CLASS_11_12", "UNDERGRADUATE", "POSTGRADUATE"],
        ["ALL_RECOGNIZED_COURSES"],
        ["STATE_GOVERNMENT", "MERIT", "INCOME"],
        60,
        500000,
        (30000, 75000),
        0,
    ),
    _scheme(
        "odisha-higher-education-merit-scholarship-2026",
        "odisha_ref",
        "Odisha Higher Education Merit Scholarship 2026–27",
        "State merit support for undergraduate and postgraduate learners.",
        ["OD"],
        ["UNDERGRADUATE", "POSTGRADUATE"],
        ["ALL_RECOGNIZED_COURSES"],
        ["STATE_GOVERNMENT", "ODISHA", "MERIT"],
        65,
        600000,
        (35000, 70000),
        1,
    ),
    _scheme(
        "gujarat-yuva-education-support-2026",
        "gujarat",
        "Gujarat Yuva Education Support Scheme 2026–27",
        "Tuition support for eligible diploma and degree students in Gujarat.",
        ["GJ"],
        ["DIPLOMA", "UNDERGRADUATE"],
        ["ALL_RECOGNIZED_COURSES"],
        ["STATE_GOVERNMENT", "GUJARAT", "MERIT", "INCOME"],
        60,
        600000,
        (40000, 90000),
        2,
    ),
    _scheme(
        "maharashtra-higher-education-fee-scholarship-2026",
        "maharashtra",
        "Maharashtra Higher Education Fee Scholarship 2026–27",
        "Fee assistance for eligible Maharashtra students in recognized programmes.",
        ["MH"],
        ["DIPLOMA", "UNDERGRADUATE", "POSTGRADUATE"],
        ["ALL_RECOGNIZED_COURSES"],
        ["STATE_GOVERNMENT", "MAHARASHTRA", "FEE_ASSISTANCE"],
        55,
        800000,
        (30000, 100000),
        3,
    ),
    _scheme(
        "karnataka-post-matric-opportunity-scholarship-2026",
        "karnataka",
        "Karnataka Post-Matric Opportunity Scholarship 2026–27",
        "Post-matric support for Karnataka students across academic levels.",
        ["KA"],
        ["CLASS_11_12", "DIPLOMA", "UNDERGRADUATE", "POSTGRADUATE"],
        ["ALL_RECOGNIZED_COURSES"],
        ["STATE_GOVERNMENT", "KARNATAKA", "POST_MATRIC"],
        55,
        600000,
        (25000, 70000),
        4,
    ),
    _scheme(
        "kerala-collegiate-merit-scholarship-2026",
        "kerala",
        "Kerala Collegiate Merit Scholarship 2026–27",
        "Merit support for students in Kerala colleges and universities.",
        ["KL"],
        ["UNDERGRADUATE", "POSTGRADUATE"],
        ["ALL_RECOGNIZED_COURSES"],
        ["STATE_GOVERNMENT", "KERALA", "MERIT"],
        70,
        600000,
        (35000, 65000),
        5,
    ),
    _scheme(
        "tamil-nadu-community-education-scholarship-2026",
        "tamil_nadu",
        "Tamil Nadu Community Education Scholarship 2026–27",
        "Post-matric support for eligible community-category learners.",
        ["TN"],
        ["CLASS_11_12", "DIPLOMA", "UNDERGRADUATE", "POSTGRADUATE"],
        ["ALL_RECOGNIZED_COURSES"],
        ["STATE_GOVERNMENT", "TAMIL_NADU", "OBC"],
        55,
        500000,
        (25000, 75000),
        0,
    ),
    _scheme(
        "telangana-fee-reimbursement-scholarship-2026",
        "telangana",
        "Telangana Fee Reimbursement Scholarship 2026–27",
        "Tuition and maintenance support for eligible Telangana learners.",
        ["TS"],
        ["CLASS_11_12", "DIPLOMA", "UNDERGRADUATE", "POSTGRADUATE"],
        ["ALL_RECOGNIZED_COURSES"],
        ["STATE_GOVERNMENT", "TELANGANA", "POST_MATRIC"],
        55,
        500000,
        (30000, 100000),
        1,
    ),
    _scheme(
        "andhra-pradesh-student-support-scholarship-2026",
        "andhra_pradesh",
        "Andhra Pradesh Student Support Scholarship 2026–27",
        "Post-matric financial assistance for eligible Andhra Pradesh students.",
        ["AP"],
        ["CLASS_11_12", "DIPLOMA", "UNDERGRADUATE", "POSTGRADUATE"],
        ["ALL_RECOGNIZED_COURSES"],
        ["STATE_GOVERNMENT", "ANDHRA_PRADESH", "POST_MATRIC"],
        55,
        500000,
        (30000, 90000),
        2,
    ),
    _scheme(
        "madhya-pradesh-medhavi-scholarship-2026",
        "madhya_pradesh",
        "Madhya Pradesh Medhavi Scholarship 2026–27",
        "Higher-education support for meritorious Madhya Pradesh students.",
        ["MP"],
        ["UNDERGRADUATE"],
        ["ALL_UNDERGRADUATE"],
        ["STATE_GOVERNMENT", "MADHYA_PRADESH", "MERIT"],
        75,
        800000,
        (50000, 120000),
        3,
    ),
    _scheme(
        "rajasthan-higher-education-scholarship-2026",
        "rajasthan",
        "Rajasthan Higher Education Scholarship 2026–27",
        "Merit-cum-means support after senior secondary education.",
        ["RJ"],
        ["UNDERGRADUATE"],
        ["ALL_UNDERGRADUATE"],
        ["STATE_GOVERNMENT", "RAJASTHAN", "MERIT", "INCOME"],
        65,
        500000,
        (35000, 70000),
        4,
    ),
    _scheme(
        "uttar-pradesh-post-matric-scholarship-2026",
        "uttar_pradesh",
        "Uttar Pradesh Post-Matric Scholarship 2026–27",
        "State support for eligible students continuing after Class 10.",
        ["UP"],
        ["CLASS_11_12", "DIPLOMA", "UNDERGRADUATE", "POSTGRADUATE"],
        ["ALL_RECOGNIZED_COURSES"],
        ["STATE_GOVERNMENT", "UTTAR_PRADESH", "POST_MATRIC"],
        55,
        500000,
        (25000, 80000),
        5,
    ),
    _scheme(
        "bihar-post-matric-progress-scholarship-2026",
        "bihar",
        "Bihar Post-Matric Progress Scholarship 2026–27",
        "Post-matric assistance for eligible Bihar students.",
        ["BR"],
        ["CLASS_11_12", "DIPLOMA", "UNDERGRADUATE", "POSTGRADUATE"],
        ["ALL_RECOGNIZED_COURSES"],
        ["STATE_GOVERNMENT", "BIHAR", "POST_MATRIC"],
        55,
        400000,
        (25000, 70000),
        0,
    ),
    _scheme(
        "jharkhand-e-kalyan-education-scholarship-2026",
        "jharkhand",
        "Jharkhand Kalyan Education Scholarship 2026–27",
        "Education assistance for eligible Jharkhand welfare-category students.",
        ["JH"],
        ["CLASS_11_12", "DIPLOMA", "UNDERGRADUATE", "POSTGRADUATE"],
        ["ALL_RECOGNIZED_COURSES"],
        ["STATE_GOVERNMENT", "JHARKHAND", "ST"],
        50,
        500000,
        (30000, 80000),
        1,
    ),
    _scheme(
        "haryana-higher-education-opportunity-scholarship-2026",
        "haryana",
        "Haryana Higher Education Opportunity Scholarship 2026–27",
        "State assistance for Haryana students in recognized higher education.",
        ["HR"],
        ["DIPLOMA", "UNDERGRADUATE", "POSTGRADUATE"],
        ["ALL_RECOGNIZED_COURSES"],
        ["STATE_GOVERNMENT", "HARYANA", "MERIT", "INCOME"],
        60,
        600000,
        (35000, 80000),
        2,
    ),
    _scheme(
        "punjab-ambedkar-post-matric-scholarship-2026",
        "punjab",
        "Punjab Ambedkar Post-Matric Scholarship 2026–27",
        "Post-matric support for eligible Punjab students from notified categories.",
        ["PB"],
        ["CLASS_11_12", "DIPLOMA", "UNDERGRADUATE", "POSTGRADUATE"],
        ["ALL_RECOGNIZED_COURSES"],
        ["STATE_GOVERNMENT", "PUNJAB", "SC"],
        50,
        500000,
        (30000, 75000),
        3,
    ),
    _scheme(
        "himachal-pradesh-girls-merit-scholarship-2026",
        "himachal_pradesh",
        "Himachal Pradesh Girls Merit Scholarship 2026–27",
        "Merit support for girl students continuing into higher education.",
        ["HP"],
        ["UNDERGRADUATE"],
        ["ALL_UNDERGRADUATE"],
        ["STATE_GOVERNMENT", "HIMACHAL_PRADESH", "WOMEN", "MERIT"],
        70,
        700000,
        (40000, 70000),
        4,
    ),
    _scheme(
        "assam-combined-merit-scholarship-2026",
        "assam",
        "Assam Combined Merit Scholarship 2026–27",
        "Merit assistance for undergraduate and postgraduate students in Assam.",
        ["AS"],
        ["UNDERGRADUATE", "POSTGRADUATE"],
        ["ALL_RECOGNIZED_COURSES"],
        ["STATE_GOVERNMENT", "ASSAM", "MERIT"],
        65,
        600000,
        (35000, 70000),
        5,
    ),
    _scheme(
        "uttarakhand-post-matric-opportunity-scholarship-2026",
        "uttarakhand",
        "Uttarakhand Post-Matric Opportunity Scholarship 2026–27",
        "Post-matric welfare support for eligible Uttarakhand students.",
        ["UK"],
        ["CLASS_11_12", "DIPLOMA", "UNDERGRADUATE", "POSTGRADUATE"],
        ["ALL_RECOGNIZED_COURSES"],
        ["STATE_GOVERNMENT", "UTTARAKHAND", "POST_MATRIC"],
        55,
        500000,
        (25000, 75000),
        0,
    ),
    _scheme(
        "chhattisgarh-post-matric-progress-scholarship-2026",
        "chhattisgarh",
        "Chhattisgarh Post-Matric Progress Scholarship 2026–27",
        "Post-matric assistance for eligible Chhattisgarh learners.",
        ["CG"],
        ["CLASS_11_12", "DIPLOMA", "UNDERGRADUATE", "POSTGRADUATE"],
        ["ALL_RECOGNIZED_COURSES"],
        ["STATE_GOVERNMENT", "CHHATTISGARH", "POST_MATRIC"],
        50,
        500000,
        (25000, 75000),
        1,
    ),
]


PRIVATE_NGO_SCHOLARSHIP_SPECS = [
    _scheme(
        "pragati-undergraduate-scholars-programme-2026",
        "reliance_foundation",
        "Pragati Undergraduate Scholars Programme 2026–27",
        "Merit-cum-means support and mentoring for first-year undergraduate students.",
        ALL_STATE_CODES,
        ["UNDERGRADUATE"],
        ["ALL_UNDERGRADUATE"],
        ["NGO", "MERIT", "INCOME"],
        65,
        600000,
        (50000, 100000),
        0,
    ),
    _scheme(
        "pragati-postgraduate-future-leaders-scholarship-2026",
        "reliance_foundation",
        "Pragati Postgraduate Future Leaders Scholarship 2026–27",
        "Postgraduate funding and mentorship in future-facing disciplines.",
        ALL_STATE_CODES,
        ["POSTGRADUATE"],
        ["STEM", "PUBLIC_POLICY", "SUSTAINABILITY"],
        ["NGO", "POSTGRADUATE", "MERIT"],
        70,
        1000000,
        (100000, 200000),
        1,
    ),
    _scheme(
        "asha-school-higher-education-scholarship-2026",
        "sbi_foundation",
        "Asha School and Higher Education Scholarship 2026–27",
        "Need-based education support spanning school and higher education.",
        ALL_STATE_CODES,
        ["CLASS_9_12", "UNDERGRADUATE", "POSTGRADUATE"],
        ["ALL_RECOGNIZED_COURSES"],
        ["NGO", "MERIT", "INCOME"],
        60,
        500000,
        (20000, 100000),
        2,
    ),
    _scheme(
        "navpragati-education-crisis-support-2026",
        "hdfc_bank",
        "NavPragati Education Crisis Support Programme 2026–27",
        "Financial support for students facing a documented family or personal crisis.",
        ALL_STATE_CODES,
        ["CLASS_9_12", "DIPLOMA", "UNDERGRADUATE", "POSTGRADUATE"],
        ["ALL_RECOGNIZED_COURSES"],
        ["PRIVATE_COMPANY", "CRISIS_SUPPORT", "INCOME"],
        55,
        500000,
        (25000, 75000),
        3,
    ),
    _scheme(
        "kanya-professional-education-scholarship-2026",
        "kotak_foundation",
        "Kanya Professional Education Scholarship 2026–27",
        "Higher-education support for meritorious women entering professional programmes.",
        ALL_STATE_CODES,
        ["UNDERGRADUATE"],
        ["PROFESSIONAL_COURSES"],
        ["NGO", "WOMEN", "MERIT", "INCOME"],
        70,
        600000,
        (75000, 150000),
        4,
    ),
    _scheme(
        "pankh-academic-scholarship-2026",
        "tata_capital",
        "Pankh Academic Scholarship 2026–27",
        "Education support for meritorious students from lower-income households.",
        ALL_STATE_CODES,
        ["CLASS_11_12", "DIPLOMA", "UNDERGRADUATE"],
        ["ALL_RECOGNIZED_COURSES"],
        ["PRIVATE_COMPANY", "MERIT", "INCOME"],
        60,
        500000,
        (30000, 90000),
        5,
    ),
    _scheme(
        "santoor-womens-higher-education-scholarship-2026",
        "wipro_cares",
        "Santoor Women's Higher Education Scholarship 2026–27",
        "Undergraduate assistance for women from underserved communities.",
        ["AP", "KA", "TS", "CG"],
        ["UNDERGRADUATE"],
        ["ALL_UNDERGRADUATE"],
        ["NGO", "WOMEN", "INCOME"],
        60,
        500000,
        (50000, 75000),
        0,
    ),
    _scheme(
        "excellence-professional-courses-scholarship-2026",
        "ffe",
        "Excellence Professional Courses Scholarship 2026–27",
        "Scholarship and mentoring for strong students in selected professional courses.",
        ALL_STATE_CODES,
        ["UNDERGRADUATE"],
        ["BTECH", "BE", "MBBS", "LAW"],
        ["NGO", "MERIT", "INCOME", "PROFESSIONAL_COURSES"],
        75,
        600000,
        (75000, 150000),
        1,
    ),
    _scheme(
        "ujjwal-smiles-foundation-scholarship-2026",
        "colgate",
        "Ujjwal Smiles Foundation Scholarship 2026–27",
        "Education support for deserving students in health and science programmes.",
        ALL_STATE_CODES,
        ["UNDERGRADUATE", "POSTGRADUATE"],
        ["BDS", "MDS", "STEM"],
        ["PRIVATE_COMPANY", "MERIT", "INCOME"],
        65,
        600000,
        (50000, 100000),
        2,
    ),
    _scheme(
        "young-women-science-scholarship-2026",
        "loreal",
        "Young Women in Science Scholarship 2026–27",
        "Science-education support for women from economically constrained backgrounds.",
        ALL_STATE_CODES,
        ["UNDERGRADUATE"],
        ["STEM", "MEDICAL"],
        ["PRIVATE_COMPANY", "WOMEN", "SCIENCE", "INCOME"],
        70,
        600000,
        (75000, 125000),
        3,
    ),
]


CATALOG_SCHOLARSHIP_SPECS = [
    *ORIGINAL_SCHOLARSHIP_SPECS,
    *CENTRAL_SCHOLARSHIP_SPECS,
    *STATE_SCHOLARSHIP_SPECS,
    *PRIVATE_NGO_SCHOLARSHIP_SPECS,
]

assert len(ORIGINAL_SCHOLARSHIP_SPECS) == 8
assert len(CENTRAL_SCHOLARSHIP_SPECS) == 20
assert len(STATE_SCHOLARSHIP_SPECS) == 20
assert len(PRIVATE_NGO_SCHOLARSHIP_SPECS) == 10
assert len(CATALOG_SCHOLARSHIP_SPECS) == 58
assert len({spec["slug"] for spec in CATALOG_SCHOLARSHIP_SPECS}) == 58
assert all(spec["required_documents"] for spec in CATALOG_SCHOLARSHIP_SPECS)
assert all(spec["eligibility_rules"] for spec in CATALOG_SCHOLARSHIP_SPECS)
assert all(spec["opens_at"] < spec["deadline_at"] for spec in CATALOG_SCHOLARSHIP_SPECS)
assert {spec["organization"] for spec in CATALOG_SCHOLARSHIP_SPECS} <= {
    spec["key"] for spec in CATALOG_ORGANIZATION_SPECS
}
